"""Credential-free constants shared by the DeepSeek CLI and provider."""

DEEPSEEK_DEFAULT_TIMEOUT_SECONDS = 120.0
DEEPSEEK_MIN_TIMEOUT_SECONDS = 30.0
DEEPSEEK_MAX_TIMEOUT_SECONDS = 300.0


__all__ = [
    "DEEPSEEK_DEFAULT_TIMEOUT_SECONDS",
    "DEEPSEEK_MAX_TIMEOUT_SECONDS",
    "DEEPSEEK_MIN_TIMEOUT_SECONDS",
]
